#
#spring.application.name=SERVICE-REGISTRY
#server.port = 8761
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

#spring:
#  profiles:
#    active: "dev"
#  config:
#    import: "optional:configserver:http://localhost:8888"
#  application:
#    name: SERVICE-REGISTRY

spring:
  application:
    name: "service"
  profiles:
    active: "discovery"

  config:
    import: "optional:configserver:http://3.132.56.186:8888"